### ISSUE TITLE
Support encrypted databases

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/cordova-plugin-sqlite-2#30]
Need to investigate different options here:
- https://www.sqlite.org/see/doc/trunk/www/readme.wiki
- https://www.zetetic.net/sqlcipher/

**Comment by ozexpert** [comment]
just read the your article, gonna try replacing with your plugin to the original sqlite plugin. 
ability to have sqlcipher would be super awesome. Also the sqlcipher adapter doesn't work with pre-populated encrypted database. It would be super awesome if it supports that.

**Comment by ozexpert** [comment]
Just a comment to tell you how this is much faster than before. Thanks for your effort!

**Comment by nolanlawson** [comment]
I have no intention or motivation ATM to support this, so closing this issue
