### ISSUE TITLE
maximum size of TEXT field and null issue

### ISSUE THREAD

**Issue by victordscott** [nolanlawson/cordova-plugin-sqlite-2#39]
When I try to store a base64 string for a photo in a text field, I don't get any errors and a record is inserted. However, when I perform a select on the record, the field that I put the base64 string into is null.   More specifically, I am storing the base64 string as a property of an object and then attempting to store the result of a JSON.stringify call.  According to the sqlite documentation, the maximum size of a text field is far larger than what I am trying to insert and retrieve.  Therefore, this seems to be a bug?

**Comment by nolanlawson** [comment]
closing old issues, please reopen as necessary. In particular it appears that this issue needs details about iOS vs Android, Cordova versions, etc. Also I am fairly sure that Android has built-in limits to the maximum size of text fields which are unavoidable, but I could be mistaken.

**Comment by nolanlawson** [comment]
possibly related: https://github.com/nolanlawson/cordova-plugin-sqlite-2/issues/46
