### ISSUE TITLE
Intel XDK: No such file or directory dist\sqlite-plugin.js

### ISSUE THREAD

**Issue by LuigiCama** [nolanlawson/cordova-plugin-sqlite-2#42]
HI !
Using Intel XDK . I tried to install your plugin it gives me this error :

Uh oh! ENOENT, no such file or directory '..\plugins\cordova-plugin-sqlite-2\dist\sqlite-plugin.js'

How can I fix ?
Thank you.
Bye.

**Comment by nolanlawson** [comment]
I didn't even know this plugin could support Intel XDK. Sorry I can't really help you. :(

**Comment by sashagrunge** [comment]
Hi,

Got the same problem on Mac

**Comment by nolanlawson** [comment]
Can you provide a test case to reproduce? Steps to install, etc.? I don't even know the first thing about Intel XDK.

**Comment by Heckscheibe** [comment]
Hi, I came across this issue as well, but I resolved it by removing the plugin and adding it again to the project. 
Cheers
