### ISSUE TITLE
Command Not Defined Error

### ISSUE THREAD

**Issue by tmorganbos** [nolanlawson/cordova-plugin-sqlite-2#48]
I've upgraded from the old cordova-plugin-sqlite to this version.

My code opens a database and I can see it when I inspect through the Safari debugger. However, any attempt to execute a transaction ends with a "Command not defined" error. It's not always caught in the debugger - I see it intermittently.

I've tried removing the plugin and platform, but this is still a problem. Any thoughts on how to fix this?

**Comment by nolanlawson** [comment]
I’ve never seen this issue, sorry. Do you have a test case to reproduce?

**Comment by tmorganbos** [comment]
I'm new to PhoneGap, picking up an app another developer wrote a while ago, and boy, do I feel dumb.

I was using a connected device and running through Phonegap desktop developer. I thought plugging a device in meant it would run on the device, but it was running on the desktop. (Stupid me)

Forcing the app to the device with the CLI solved the problem.
