### ISSUE TITLE
Conflict with cordova-sqlite-storage

### ISSUE THREAD

**Issue by aiaf** [nolanlawson/cordova-plugin-sqlite-2#49]
Cannot build for iOS with cordova-plugin-sqlite-2 and litehelpers/Cordova-sqlite-storage in the same Ionic 2 project. 

Build fails with `duplicate symbol _OBJC_CLASS_$_SQLitePlugin`

Perhaps prefixing the classnames with a namespace as is customary for Cocoa projects would be a solution.

**Comment by nolanlawson** [comment]
Those two libraries are competitors, not complementary packages. They both add the same object, called `SQLitePlugin`. ideally you should use one or the other, not both.
