### ISSUE TITLE
Problems sqlite in IOS 11

### ISSUE THREAD

**Issue by koronaldo** [nolanlawson/cordova-plugin-sqlite-2#53]
Good Morning.

I have a problem that I could not solve, could you help me?

I have an application that I developed with Cordova 7.1.0, I added the Cordova-sqlite-storage plugin. In android works that is a blz. already in the ios it does not rotate. It opens the connection to the bank, but when it arrives in db.transaction it hangs, minutes later it executes, it takes in average 3 minutes to respond. I tried several plugins and I had the same problem, I do not know what I can test, it does not generate any type of error, it only slows down and it takes a while to return.

Thank you.

**Comment by koronaldo** [comment]
Sorry I´m using plugin cordova-plugin-sqlite-2

**Comment by nolanlawson** [comment]
Are you using both Cordova-sqlite-storage and cordova-plugin-sqlite-2? Do you havea  test case to repro?

Closing old issues, please reopen as necessary :)
