### ISSUE TITLE
Unexpected EOF

### ISSUE THREAD

**Issue by ccorcos** [nolanlawson/cordova-plugin-sqlite-2#54]
It looks like theres an issue with `\u2028` and `\u2029`. When I wrote this string to the database and when I tried to retrieve the document,  I got `SyntaxError: Unexpected EOF` and the database was unresponsive.

- https://github.com/pouchdb/pouchdb/issues/5618

**Comment by ccorcos** [comment]
Also `\u2008`

**Comment by nolanlawson** [comment]
discussion in that issue suggests this is a bug in Cordova itself (https://github.com/apache/cordova-discuss/issues/57), closing
