### ISSUE TITLE
Warning: db.type() is deprecated and will be removed

### ISSUE THREAD

**Issue by heikoholland** [nolanlawson/cordova-plugin-sqlite-2#56]
I'm using this plugin in an ionic1 app.

`bower.json`
```
"angular-pouchdb": "5.0.1",
"pouchdb-find": "0.10.5"
```

`config.xml`
```
<plugin name="cordova-plugin-sqlite-2" spec="^1.0.4" />
```

On every action PouchDB does I'm getting the warning `Warning: db.type() is deprecated and will be removed`.

This plugin needs some updates :)

**Comment by lochehong** [comment]
are you using the pouchDB adapter?

**Comment by heikoholland** [comment]
Yes I was using it on iPad but I switched back to IndexedDB because of another issue I got with iOS 11.2.

**Comment by lochehong** [comment]
did you manage to fix the db.type() warnings or find out where it was coming from?

do you know if indexedDB have storage limits? i know indexedDB is faster option.

Chris

**Comment by heikoholland** [comment]
I just know it's coming from this plugin but didn't look where and why. I just switched back because I didn't know why I switched vom IndexedDB to SQLite anyways.

I read about a 50mb storage limit on iOS yesterday but I can't find it today.

**Comment by nolanlawson** [comment]
You're probably running into this issue because pouchdb-find or another PouchDB plugin is out-of-date relative to PouchDB. This library has nothing to do with PouchDB and so is probably not the source of the problem.

Closing old issues, please reopen as necessary...
