### ISSUE TITLE
doc clarify on wkwebview websql usage

### ISSUE THREAD

**Issue by mzealey** [nolanlawson/cordova-plugin-sqlite-2#63]
Just to clarify, WebSQL was not available in WkWebView on IOS9 and early betas of IOS10, but is avaliable in all current versions of IOS10/11 and works well. In fact, an alternative to using this plugin on ios may be to use my slightly hacked version of the ionic wkwebview code (https://github.com/mzealey/cordova-plugin-ionic-webview) which just implements wkwebview on ios10 and higher. This works fine for a WebSQL-heavy project with many users that I develop.

**Comment by nolanlawson** [comment]
Thanks for clarifying, I wasn't aware of this. I'll update the readme!
