### ISSUE TITLE
Please update plugin version to 1.0.5 in plugin.xml file. 

### ISSUE THREAD

**Issue by platov** [nolanlawson/cordova-plugin-sqlite-2#72]
After release of `1.0.5` version the `plugin.xml` still declares `1.0.4`
https://github.com/nolanlawson/cordova-plugin-sqlite-2/blob/959743b2ed97fa1468076c1725a54e7a472b67b6/plugin.xml#L2-L3

**Comment by nolanlawson** [comment]
Thanks for reporting, fixed in 1.0.6!
