### ISSUE TITLE
When adding this plugin I am getting this error in Cordova

### ISSUE THREAD

**Issue by Durgavenkataprasad** [nolanlawson/cordova-plugin-sqlite-2#74]
[
<img width="720" alt="Screenshot 2019-11-21 at 10 59 38 PM" src="https://user-images.githubusercontent.com/43673091/69363420-80a37a80-0cb6-11ea-9d96-0c1fe342be91.png">
](url)

**Comment by Durgavenkataprasad** [comment]
See **sqlite-plugin.js** no such file error

**Comment by nolanlawson** [comment]
It seems that the plugin failed to install (e.g. via `npm install`). If this is still an issue, please reopen, thanks!
