### ISSUE TITLE
PouchDB error: you must install a SQLite plugin in order for PouchDB to work on this platform.

### ISSUE THREAD

**Issue by dhruvsingh50** [nolanlawson/cordova-plugin-sqlite-2#75]
Hi, 
I have installed the /cordova-plugin-sqlite-2 but still getting this error. 

 PouchDB error: you must install a SQLite plugin in order for PouchDB to work on this platform. Options:
 - https://github.com/nolanlawson/cordova-plugin-sqlite-2
 - https://github.com/litehelpers/Cordova-sqlite-storage
 - https://github.com/Microsoft/cordova-plugin-websql

 

` if (typeof cordova === 'undefined' || (typeof sqlitePlugin === 'undefined' && typeof openDatabase === 'undefined')) ---> this line is giving error`

My code : 
```
    **this.db =  new PouchDB(this.name, {adapter: 'cordova-sqlite'});
    console.log(this.db);**

```
**console output:** 

app-logs: LogStorage
db: PouchDB
adapter: "cordova-sqlite"
auto_compaction: undefined
name: "app-logs"
prefix: "_pouch_"
taskqueue: TaskQueue$1 {isReady: true, failed: false, queue: Array(0), db: PouchDB}
type: ƒ ()
__opts: {adapter: "cordova-sqlite", name: "app-logs"}
_adapter: "cordova-sqlite"
_allDocs: ƒ (opts, callback)
_bulkDocs: ƒ (req, reqOpts, callback)
_cachedViews: {{"fields":{"pd_index":"asc","pd_type":"asc"}}_countundefined: t}
_changes: ƒ (opts)
_close: ƒ (callback)
_destroy: ƒ (opts, callback)
_doCompaction: ƒ (docId, revs, callback)
_events: {destroyed: Array(1), closed: ƒ}
_get: ƒ (id, opts, callback)
_getAttachment: ƒ (docId, attachId, attachment, opts, callback)
_getLocal: ƒ (id, callback)
_getRevisionTree: ƒ (docId, callback)
_id: ƒ ()
_info: ƒ (callback)
_maxListeners: undefined
_name: "app-logs"
_putLocal: ƒ (doc, opts, callback)
_remote: false
_removeLocal: ƒ (doc, opts, callback)
replicate: (...)
__proto__: AbstractPouchDB

**Comment by marionava** [comment]
I'm having exactly the same issue!

**Comment by marionava** [comment]
Hi @dhruvsingh50. Do you find any solution for this?

**Comment by marionava** [comment]
I hope this helps you. SQLite Plugin does not work on the browser. Until I tested it with my iOS device and made a few slight changes to my code it worked perfectly, but only on a real device. This is what I changed on my code:

```
PouchDB.plugin(SQLitePlugin);
this.db =  new PouchDB(this.name, {
            adapter: 'cordova-sqlite',
            iosDatabaseLocation: 'Library',
            androidDatabaseImplementation: 2
        });
```

**Comment by nolanlawson** [comment]
^ This is the right solution. SQLite plugin 2 runs in a WebView, not in a browser.
