### ISSUE TITLE
Unhandled Promise Rejection: TypeError: JSON.stringify cannot serialize cyclic structures

### ISSUE THREAD

**Issue by yoprogramo** [nolanlawson/cordova-plugin-sqlite-2#77]
I have a websql database that I'm trying to convert (apple does not support anymore websql) and my table have a field with the same name of the table (in the table I have problems with) and, when I try to insert some values I receive this error:

Unhandled Promise Rejection: TypeError: JSON.stringify cannot serialize cyclic structures.
callbackFromNative — cordova.js:314
(anonymous function) — cordova.js:972
promiseReactionJob

For compatibility reasons I cannot just change the name of the fields/table. There exist some other workaround?

**Comment by nolanlawson** [comment]
Sounds like you found a workaround?

**Comment by yoprogramo** [comment]
Yes, it was my fault trying to store a wrong value for the column. Fixed already in my code.
