### ISSUE TITLE
What import statement should be used for using this plugin in Ionic ?

### ISSUE THREAD

**Issue by pratiksan45** [nolanlawson/cordova-plugin-sqlite-2#78]
Hi, I have installed this plugin in my Ionic framework using the command "npm i cordova-plugin-sqlite-2" but to use it's features for creating database, what should be my import statement  i.e  "import { ____ } from '@ionic-____/___';

**Comment by nolanlawson** [comment]
I'm not familiar with how Ionic works, but I believe Cordova plugins are just added to the `window` object. So it should be just `window.sqlitePlugin`. Let me know if that helps! If not, you might try StackOverflow.

**Comment by faugusztin** [comment]
Plugin being a drop-in replacement of cordova-sqlite-storage, you need to look at sqlite docs at Ionic native https://ionicframework.com/docs/native/sqlite .
